### ISSUE TITLE
Summarization error

### ISSUE THREAD

**Issue by DannyPio01** [dcSpark/shinkai-node#434]
Theirs an error with project summarization due to the vector resource 
VectorResource error: Failed to parse Unstructed API response json: Response is not an array at top level: : {"detail":"Server is under heavy load. Please try again later."}

**Comment by nicarq** [comment]
it should be fixed. thanks for creating the issue! we are also releasing soon a new tool to parse files locally that doesn't require some extra installation like unstructure.io
